#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'soc_system' in
 * file '/home/letrend/workspace/DarkRoom/src/DarkRoom_fpga/roboy_de10_nano_soc/soc_system.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following masters:
 *   h2f_axi_master
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'DarkRoom_0', class 'DarkRoom'
 * The macros are prefixed with 'DARKROOM_0_'.
 * The prefix is the slave descriptor.
 */
#define DARKROOM_0_COMPONENT_TYPE DarkRoom
#define DARKROOM_0_COMPONENT_NAME DarkRoom_0
#define DARKROOM_0_BASE 0x800
#define DARKROOM_0_SPAN 256
#define DARKROOM_0_END 0x8ff


#endif /* _ALTERA_HPS_0_H_ */
